# igtp_config.yaml

# File paths and directories
# sc_data_path: "/rsrch5/home/gen_med_onc_rsch/khsieh/single_cell_pdx/data/pdx_combined.h5ad"
# tp_file_path: "/rsrch5/home/gen_med_onc_rsch/khsieh/single_cell_pdx/TP/hall_mark.gmt"
# ppi_file_path: "/rsrch5/home/gen_med_onc_rsch/khsieh/single_cell_pdx/PPI/PC_homo_v11.txt"
# model_dir: "/rsrch5/home/gen_med_onc_rsch/khsieh/single_cell_pdx/save_model/mice/"

# File paths and directories
sc_data_path: "/rsrch8/home/imag_phy-rsrch/kzhang7/Yulin/iGTP_data/test_data/pbmc_IFN_filtered_1.h5ad"
tp_file_path: "/rsrch8/home/imag_phy-rsrch/kzhang7/Yulin/iGTP_data/test_data/hall_mark.gmt"
ppi_file_path: "/rsrch8/home/imag_phy-rsrch/kzhang7/Yulin/iGTP_data/test_data/PC_homo_v11.txt"
model_dir: "/rsrch8/home/imag_phy-rsrch/kzhang7/Yulin/iGTP/save_model/mice/"


# Model parameters
tp_overlap_fraction: 0.1
encoder_layer_list: [1500]
beta: 0.00005
encoder_normal: 'batch'
init_type: 'pos_uniform'
recon_loss: 'mse'
drop_out: 0.2
eps: 0.001
cv_fold: 3
learning_rate: 0.001
learning_rate_weight_decay: 0.000054
n_epochs: 500
train_patience: 10
test_patience: 10
data_num_workers: 1
save_fold: true
save_best: true
anneal_start: null
anneal_time: null
vb_nu: 15000
batch_size: 4000
drop_last_batch: false
device_nu: 0
using_gpu: true
z_sample: 1