# igtp_config.yaml

# File paths and directories
processed_data_path: "/rsrch5/home/gen_med_onc_rsch/khsieh/single_cell_pdx/save_model/mice/processed_data/hall_mark_PC_homo_v11_mse_pos_uniform_15000batch.pkl"
output_folder: "/rsrch5/home/gen_med_onc_rsch/khsieh/single_cell_pdx/result/"
